### PR TITLE
Many typos fixed

### PR DESCRIPTION
**Pull request by marijneken**
Wow, this is two years later. I made the fixes a long time ago, but never sent them in. But here they are now.. It looks like nothing was committed in the mean time, so it should be an easy 'merge'.

### CODE REVIEW

**Comment by nVoid** [comment]
Hi Marjin! Thanks for submitting those. Much appreciated :) It's reporting a few conflicts but they should be easy to fix. I'll have a look over the next few days and merge them in.

**Comment by interactiveimmersivehq** [comment]
Hi @marijneken  thanks for these. Sorry about such a long delay in getting to processing these. The only changes I didn't merge in are the ones regarding previous Latex notation like {}, as I'm going to do a full sweep of the book and update those separately now. Do you want to also send me how you'd like your name to appear in the credits?

**Comment by marijneken** [comment]
Not sure if it really warrants a credit, but my name should be written as: Marijn Eken

**Comment by interactiveimmersivehq** [comment]
Any contribution is a valid one that deserves attribution :) thanks @marijneken !

**Pull request merged**
